# Generated by Django 4.2.6 on 2023-11-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='iamge',
            new_name='image',
        ),
    ]
