# Generated by Django 4.2.6 on 2023-11-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='payment_intent',
            new_name='stripe_payment_intent',
        ),
    ]
