# Generated by Django 4.2.6 on 2023-11-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_payment_intent_orderdetail_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='stripe_payment_intent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
